---
# Source: simple-app-runner/templates/claims.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: simple-app-runner-RELEASE-NAME-claim1
  labels:
    app: simple-app-runner
    chart: "simple-app-runner-1.14"
    release: RELEASE-NAME
    heritage: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: ""
---
# Source: simple-app-runner/templates/4.0.service.yaml
apiVersion: v1
kind: Service
metadata:
  name: simple-app-runner-RELEASE-NAME
  labels:
    app: simple-app-runner
    chart: "simple-app-runner-1.14"
    release: RELEASE-NAME
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: app-http
      protocol: TCP
  selector:
    app: simple-app-runner-RELEASE-NAME
---
# Source: simple-app-runner/templates/3.deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: simple-app-runner-RELEASE-NAME
  labels:
    app: simple-app-runner
    chart: "simple-app-runner-1.14"
    release: RELEASE-NAME
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: simple-app-runner-RELEASE-NAME
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 30 
  template:
    metadata:
      labels:
        app: simple-app-runner-RELEASE-NAME
      annotations: 
        timestamp: "2021-09-07T09:51:31Z"
    spec:
      containers:
        - name: "simple-app-runner"
          image: "hello-world:latest"
          env:
            - name: VAR111
              value: asd33
          ports:
            - name: app-http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: app-http
            initialDelaySeconds: 300
            timeoutSeconds: 30
---
# Source: simple-app-runner/templates/5.0.ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-app-runner-RELEASE-NAME
  labels:
    app: simple-app-runner
    chart: "simple-app-runner-1.14"
    release: RELEASE-NAME
    heritage: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
spec:
  tls:
  - hosts:
    - server.k1.domain.tld
    secretName: tls-simple-app-runner-RELEASE-NAME
  rules:
  - host: server.k1.domain.tld
    http:
      paths:
      - path: /
        backend:
          serviceName: simple-app-runner-RELEASE-NAME
          servicePort: 80
