{{- if .Values.app.cronjob.enabled -}}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.app.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.app.cronjob.successfulJobsHistoryLimit | default "1" }}
  failedJobsHistoryLimit: {{ .Values.app.cronjob.failedJobsHistoryLimit | default "1" }}
  concurrencyPolicy: {{ .Values.app.cronjob.concurrencyPolicy | default "Forbid" }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.app.cronjob.backoffLimit | default "0" }}
{{- if .Values.app.cronjob.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.app.cronjob.activeDeadlineSeconds }}
{{- end }}
      template:
        metadata:
          labels:
            app: {{ template "app.fullname" . }}
{{- if .Values.app.recreatePod }}
          annotations: 
            timestamp: {{ now | date "2006-01-02T15:04:05Z" | quote }}
{{- end }}
        spec:
          restartPolicy: Never
{{- if .Values.app.image.pullSecret }}
          imagePullSecrets:
            - name: {{ .Values.app.image.pullSecret }}
{{- end }}
          containers:
            - name: {{ .Chart.Name | quote }}
              image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
{{- if .Values.app.image.pullPolicy }}
              imagePullPolicy: {{ .Values.app.image.pullPolicy }}
{{- end }}
{{- if .Values.app.image.command }}
              command: #[ {{ .Values.app.image.command | quote }} ] #['/bin/sh', '-c', 'while true; do echo hello; sleep 10;done']
{{- range $cmd := .Values.app.image.command }}
                - {{ $cmd | quote }}
{{- end }}
{{- end }}
{{- if .Values.app.resources }}
              resources:
{{ toYaml .Values.app.resources | indent 16 }}
{{- end }}
{{- if .Values.app.env }}
              env:
{{- range $key, $value := .Values.app.env }}
                - name: {{ $key }}
{{- if kindIs "string" $value }}
                  value: {{ $value | quote }}
{{- else }}
{{ toYaml $value | indent 18 }}
{{- end }}
{{- end }}
{{- end }}
{{- if or .Values.app.secrets (or .Values.app.configs .Values.app.volumes) }}           
              volumeMounts:
{{- if .Values.app.secrets }}
{{- range $i, $secret := .Values.app.secrets }}
{{- if $secret.path }}
                - name: secret{{ $i | add1 }}
                  mountPath: {{ $secret.path }}/{{ $secret.name }}
                  subPath: {{ $secret.name }}
                  readOnly: true
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.app.configs }}
{{- range $i, $config := .Values.app.configs }}
                - name: config{{ $i | add1 }}
                  mountPath: {{ $config.path }}/{{ $config.name }}
                  subPath: {{ $config.name }}
                  readOnly: true
{{- end }}
{{- end }}
{{- if .Values.app.volumes }}
{{- range $i, $volume := .Values.app.volumes }}
                - name: volume{{ $i | add1 }}-{{ $volume.name }}
                  mountPath: {{ $volume.mountPath }}
{{- if $volume.subPath }}
                  subPath: {{ $volume.subPath }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if or .Values.app.secrets (or .Values.app.configs .Values.app.volumes) }}
          volumes:
{{- if .Values.app.secrets }}
{{- range $i, $secret := .Values.app.secrets }}
{{- if $secret.path }}
            - name: secret{{ $i | add1 }}
              secret:
                secretName: {{ template "app.fullname" $ }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.app.configs }}
{{- range $i, $config := .Values.app.configs }}
            - name: config{{ $i | add1 }}
              configMap:
                name: {{ template "app.fullname" $ }}
{{- end }}
{{- end }}
{{- if .Values.app.volumes }}
{{- range $i, $volume := .Values.app.volumes }}
            - name: volume{{ $i | add1 }}-{{ $volume.name }}
{{- if $volume.spec }}
{{ toYaml $volume.spec | indent 14 }}
{{- end }}
{{- if $volume.claimName }}
              persistentVolumeClaim:
                claimName: {{ printf "%s-%s" (include "app.fullname" $) $volume.claimName }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}